name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.5.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
  fonts:
    - family: Nexa
      fonts:
        - asset: lib/assets/fonts/Nexa-ExtraLight.ttf
          weight: 300
        - asset: lib/assets/fonts/Nexa-Heavy.ttf
          weight: 700